// +build !ignore_autogenerated

/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	identity "go.bytebuilders.dev/resource-model/apis/identity"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Snapshot)(nil), (*identity.Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Snapshot_To_identity_Snapshot(a.(*Snapshot), b.(*identity.Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*identity.Snapshot)(nil), (*Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_identity_Snapshot_To_v1alpha1_Snapshot(a.(*identity.Snapshot), b.(*Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotList)(nil), (*identity.SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotList_To_identity_SnapshotList(a.(*SnapshotList), b.(*identity.SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*identity.SnapshotList)(nil), (*SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_identity_SnapshotList_To_v1alpha1_SnapshotList(a.(*identity.SnapshotList), b.(*SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotStatus)(nil), (*identity.SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus(a.(*SnapshotStatus), b.(*identity.SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*identity.SnapshotStatus)(nil), (*SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus(a.(*identity.SnapshotStatus), b.(*SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Snapshot_To_identity_Snapshot(in *Snapshot, out *identity.Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Snapshot_To_identity_Snapshot is an autogenerated conversion function.
func Convert_v1alpha1_Snapshot_To_identity_Snapshot(in *Snapshot, out *identity.Snapshot, s conversion.Scope) error {
	return autoConvert_v1alpha1_Snapshot_To_identity_Snapshot(in, out, s)
}

func autoConvert_identity_Snapshot_To_v1alpha1_Snapshot(in *identity.Snapshot, out *Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_identity_Snapshot_To_v1alpha1_Snapshot is an autogenerated conversion function.
func Convert_identity_Snapshot_To_v1alpha1_Snapshot(in *identity.Snapshot, out *Snapshot, s conversion.Scope) error {
	return autoConvert_identity_Snapshot_To_v1alpha1_Snapshot(in, out, s)
}

func autoConvert_v1alpha1_SnapshotList_To_identity_SnapshotList(in *SnapshotList, out *identity.SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]identity.Snapshot, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Snapshot_To_identity_Snapshot(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_SnapshotList_To_identity_SnapshotList is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotList_To_identity_SnapshotList(in *SnapshotList, out *identity.SnapshotList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotList_To_identity_SnapshotList(in, out, s)
}

func autoConvert_identity_SnapshotList_To_v1alpha1_SnapshotList(in *identity.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Snapshot, len(*in))
		for i := range *in {
			if err := Convert_identity_Snapshot_To_v1alpha1_Snapshot(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_identity_SnapshotList_To_v1alpha1_SnapshotList is an autogenerated conversion function.
func Convert_identity_SnapshotList_To_v1alpha1_SnapshotList(in *identity.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	return autoConvert_identity_SnapshotList_To_v1alpha1_SnapshotList(in, out, s)
}

func autoConvert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus(in *SnapshotStatus, out *identity.SnapshotStatus, s conversion.Scope) error {
	out.Tree = in.Tree
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	out.Hostname = in.Hostname
	out.Username = in.Username
	out.UID = int(in.UID)
	out.Gid = int(in.Gid)
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus(in *SnapshotStatus, out *identity.SnapshotStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotStatus_To_identity_SnapshotStatus(in, out, s)
}

func autoConvert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *identity.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	out.Tree = in.Tree
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	out.Hostname = in.Hostname
	out.Username = in.Username
	out.UID = int32(in.UID)
	out.Gid = int32(in.Gid)
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus is an autogenerated conversion function.
func Convert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *identity.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	return autoConvert_identity_SnapshotStatus_To_v1alpha1_SnapshotStatus(in, out, s)
}
