/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cloud/v1alpha1"
	scheme "go.bytebuilders.dev/resource-model/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CloudProvidersGetter has a method to return a CloudProviderInterface.
// A group's client should implement this interface.
type CloudProvidersGetter interface {
	CloudProviders() CloudProviderInterface
}

// CloudProviderInterface has methods to work with CloudProvider resources.
type CloudProviderInterface interface {
	Create(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.CreateOptions) (*v1alpha1.CloudProvider, error)
	Update(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.UpdateOptions) (*v1alpha1.CloudProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CloudProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CloudProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudProvider, err error)
	CloudProviderExpansion
}

// cloudProviders implements CloudProviderInterface
type cloudProviders struct {
	client rest.Interface
}

// newCloudProviders returns a CloudProviders
func newCloudProviders(c *CloudV1alpha1Client) *cloudProviders {
	return &cloudProviders{
		client: c.RESTClient(),
	}
}

// Get takes name of the cloudProvider, and returns the corresponding cloudProvider object, and an error if there is any.
func (c *cloudProviders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CloudProvider, err error) {
	result = &v1alpha1.CloudProvider{}
	err = c.client.Get().
		Resource("cloudproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CloudProviders that match those selectors.
func (c *cloudProviders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CloudProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CloudProviderList{}
	err = c.client.Get().
		Resource("cloudproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cloudProviders.
func (c *cloudProviders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("cloudproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cloudProvider and creates it.  Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *cloudProviders) Create(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.CreateOptions) (result *v1alpha1.CloudProvider, err error) {
	result = &v1alpha1.CloudProvider{}
	err = c.client.Post().
		Resource("cloudproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cloudProvider).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cloudProvider and updates it. Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *cloudProviders) Update(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.UpdateOptions) (result *v1alpha1.CloudProvider, err error) {
	result = &v1alpha1.CloudProvider{}
	err = c.client.Put().
		Resource("cloudproviders").
		Name(cloudProvider.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cloudProvider).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cloudProvider and deletes it. Returns an error if one occurs.
func (c *cloudProviders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("cloudproviders").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cloudProviders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("cloudproviders").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cloudProvider.
func (c *cloudProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudProvider, err error) {
	result = &v1alpha1.CloudProvider{}
	err = c.client.Patch(pt).
		Resource("cloudproviders").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
