/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cluster/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterCredentials implements ClusterCredentialInterface
type FakeClusterCredentials struct {
	Fake *FakeClusterV1alpha1
}

var clustercredentialsResource = schema.GroupVersionResource{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Resource: "clustercredentials"}

var clustercredentialsKind = schema.GroupVersionKind{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Kind: "ClusterCredential"}

// Get takes name of the clusterCredential, and returns the corresponding clusterCredential object, and an error if there is any.
func (c *FakeClusterCredentials) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustercredentialsResource, name), &v1alpha1.ClusterCredential{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredential), err
}

// List takes label and field selectors, and returns the list of ClusterCredentials that match those selectors.
func (c *FakeClusterCredentials) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterCredentialList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustercredentialsResource, clustercredentialsKind, opts), &v1alpha1.ClusterCredentialList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterCredentialList{ListMeta: obj.(*v1alpha1.ClusterCredentialList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterCredentialList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterCredentials.
func (c *FakeClusterCredentials) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustercredentialsResource, opts))
}

// Create takes the representation of a clusterCredential and creates it.  Returns the server's representation of the clusterCredential, and an error, if there is any.
func (c *FakeClusterCredentials) Create(ctx context.Context, clusterCredential *v1alpha1.ClusterCredential, opts v1.CreateOptions) (result *v1alpha1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustercredentialsResource, clusterCredential), &v1alpha1.ClusterCredential{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredential), err
}

// Update takes the representation of a clusterCredential and updates it. Returns the server's representation of the clusterCredential, and an error, if there is any.
func (c *FakeClusterCredentials) Update(ctx context.Context, clusterCredential *v1alpha1.ClusterCredential, opts v1.UpdateOptions) (result *v1alpha1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustercredentialsResource, clusterCredential), &v1alpha1.ClusterCredential{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredential), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterCredentials) UpdateStatus(ctx context.Context, clusterCredential *v1alpha1.ClusterCredential, opts v1.UpdateOptions) (*v1alpha1.ClusterCredential, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustercredentialsResource, "status", clusterCredential), &v1alpha1.ClusterCredential{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredential), err
}

// Delete takes name of the clusterCredential and deletes it. Returns an error if one occurs.
func (c *FakeClusterCredentials) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustercredentialsResource, name), &v1alpha1.ClusterCredential{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterCredentials) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustercredentialsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterCredentialList{})
	return err
}

// Patch applies the patch and returns the patched clusterCredential.
func (c *FakeClusterCredentials) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustercredentialsResource, name, pt, data, subresources...), &v1alpha1.ClusterCredential{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterCredential), err
}
