/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cluster/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterInfos implements ClusterInfoInterface
type FakeClusterInfos struct {
	Fake *FakeClusterV1alpha1
}

var clusterinfosResource = schema.GroupVersionResource{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Resource: "clusterinfos"}

var clusterinfosKind = schema.GroupVersionKind{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Kind: "ClusterInfo"}

// Get takes name of the clusterInfo, and returns the corresponding clusterInfo object, and an error if there is any.
func (c *FakeClusterInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterinfosResource, name), &v1alpha1.ClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInfo), err
}

// List takes label and field selectors, and returns the list of ClusterInfos that match those selectors.
func (c *FakeClusterInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterinfosResource, clusterinfosKind, opts), &v1alpha1.ClusterInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterInfoList{ListMeta: obj.(*v1alpha1.ClusterInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterInfos.
func (c *FakeClusterInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterinfosResource, opts))
}

// Create takes the representation of a clusterInfo and creates it.  Returns the server's representation of the clusterInfo, and an error, if there is any.
func (c *FakeClusterInfos) Create(ctx context.Context, clusterInfo *v1alpha1.ClusterInfo, opts v1.CreateOptions) (result *v1alpha1.ClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterinfosResource, clusterInfo), &v1alpha1.ClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInfo), err
}

// Update takes the representation of a clusterInfo and updates it. Returns the server's representation of the clusterInfo, and an error, if there is any.
func (c *FakeClusterInfos) Update(ctx context.Context, clusterInfo *v1alpha1.ClusterInfo, opts v1.UpdateOptions) (result *v1alpha1.ClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterinfosResource, clusterInfo), &v1alpha1.ClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterInfos) UpdateStatus(ctx context.Context, clusterInfo *v1alpha1.ClusterInfo, opts v1.UpdateOptions) (*v1alpha1.ClusterInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterinfosResource, "status", clusterInfo), &v1alpha1.ClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInfo), err
}

// Delete takes name of the clusterInfo and deletes it. Returns an error if one occurs.
func (c *FakeClusterInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterinfosResource, name, opts), &v1alpha1.ClusterInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterInfoList{})
	return err
}

// Patch applies the patch and returns the patched clusterInfo.
func (c *FakeClusterInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterinfosResource, name, pt, data, subresources...), &v1alpha1.ClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInfo), err
}
