/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cluster/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterAuthInfoTemplates implements ClusterAuthInfoTemplateInterface
type FakeClusterAuthInfoTemplates struct {
	Fake *FakeClusterV1alpha1
}

var clusterauthinfotemplatesResource = schema.GroupVersionResource{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Resource: "clusterauthinfotemplates"}

var clusterauthinfotemplatesKind = schema.GroupVersionKind{Group: "cluster.bytebuilders.dev", Version: "v1alpha1", Kind: "ClusterAuthInfoTemplate"}

// Get takes name of the clusterAuthInfoTemplate, and returns the corresponding clusterAuthInfoTemplate object, and an error if there is any.
func (c *FakeClusterAuthInfoTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterAuthInfoTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterauthinfotemplatesResource, name), &v1alpha1.ClusterAuthInfoTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), err
}

// List takes label and field selectors, and returns the list of ClusterAuthInfoTemplates that match those selectors.
func (c *FakeClusterAuthInfoTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterAuthInfoTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterauthinfotemplatesResource, clusterauthinfotemplatesKind, opts), &v1alpha1.ClusterAuthInfoTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterAuthInfoTemplateList{ListMeta: obj.(*v1alpha1.ClusterAuthInfoTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterAuthInfoTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterAuthInfoTemplates.
func (c *FakeClusterAuthInfoTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterauthinfotemplatesResource, opts))
}

// Create takes the representation of a clusterAuthInfoTemplate and creates it.  Returns the server's representation of the clusterAuthInfoTemplate, and an error, if there is any.
func (c *FakeClusterAuthInfoTemplates) Create(ctx context.Context, clusterAuthInfoTemplate *v1alpha1.ClusterAuthInfoTemplate, opts v1.CreateOptions) (result *v1alpha1.ClusterAuthInfoTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterauthinfotemplatesResource, clusterAuthInfoTemplate), &v1alpha1.ClusterAuthInfoTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), err
}

// Update takes the representation of a clusterAuthInfoTemplate and updates it. Returns the server's representation of the clusterAuthInfoTemplate, and an error, if there is any.
func (c *FakeClusterAuthInfoTemplates) Update(ctx context.Context, clusterAuthInfoTemplate *v1alpha1.ClusterAuthInfoTemplate, opts v1.UpdateOptions) (result *v1alpha1.ClusterAuthInfoTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterauthinfotemplatesResource, clusterAuthInfoTemplate), &v1alpha1.ClusterAuthInfoTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterAuthInfoTemplates) UpdateStatus(ctx context.Context, clusterAuthInfoTemplate *v1alpha1.ClusterAuthInfoTemplate, opts v1.UpdateOptions) (*v1alpha1.ClusterAuthInfoTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterauthinfotemplatesResource, "status", clusterAuthInfoTemplate), &v1alpha1.ClusterAuthInfoTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), err
}

// Delete takes name of the clusterAuthInfoTemplate and deletes it. Returns an error if one occurs.
func (c *FakeClusterAuthInfoTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterauthinfotemplatesResource, name, opts), &v1alpha1.ClusterAuthInfoTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterAuthInfoTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterauthinfotemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterAuthInfoTemplateList{})
	return err
}

// Patch applies the patch and returns the patched clusterAuthInfoTemplate.
func (c *FakeClusterAuthInfoTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAuthInfoTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterauthinfotemplatesResource, name, pt, data, subresources...), &v1alpha1.ClusterAuthInfoTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), err
}
