/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cluster/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterAuthInfoTemplateLister helps list ClusterAuthInfoTemplates.
type ClusterAuthInfoTemplateLister interface {
	// List lists all ClusterAuthInfoTemplates in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterAuthInfoTemplate, err error)
	// Get retrieves the ClusterAuthInfoTemplate from the index for a given name.
	Get(name string) (*v1alpha1.ClusterAuthInfoTemplate, error)
	ClusterAuthInfoTemplateListerExpansion
}

// clusterAuthInfoTemplateLister implements the ClusterAuthInfoTemplateLister interface.
type clusterAuthInfoTemplateLister struct {
	indexer cache.Indexer
}

// NewClusterAuthInfoTemplateLister returns a new ClusterAuthInfoTemplateLister.
func NewClusterAuthInfoTemplateLister(indexer cache.Indexer) ClusterAuthInfoTemplateLister {
	return &clusterAuthInfoTemplateLister{indexer: indexer}
}

// List lists all ClusterAuthInfoTemplates in the indexer.
func (s *clusterAuthInfoTemplateLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterAuthInfoTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterAuthInfoTemplate))
	})
	return ret, err
}

// Get retrieves the ClusterAuthInfoTemplate from the index for a given name.
func (s *clusterAuthInfoTemplateLister) Get(name string) (*v1alpha1.ClusterAuthInfoTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterauthinfotemplate"), name)
	}
	return obj.(*v1alpha1.ClusterAuthInfoTemplate), nil
}
