//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcePlatformAdmin) DeepCopyInto(out *AcePlatformAdmin) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcePlatformAdmin.
func (in *AcePlatformAdmin) DeepCopy() *AcePlatformAdmin {
	if in == nil {
		return nil
	}
	out := new(AcePlatformAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AceSetupConfig) DeepCopyInto(out *AceSetupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Nats = in.Nats
	in.AceSetupInlineConfig.DeepCopyInto(&out.AceSetupInlineConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AceSetupConfig.
func (in *AceSetupConfig) DeepCopy() *AceSetupConfig {
	if in == nil {
		return nil
	}
	out := new(AceSetupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AceSetupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AceSetupInlineConfig) DeepCopyInto(out *AceSetupInlineConfig) {
	*out = *in
	out.Admin = in.Admin
	in.SelfManagement.DeepCopyInto(&out.SelfManagement)
	out.MarketplaceInfo = in.MarketplaceInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AceSetupInlineConfig.
func (in *AceSetupInlineConfig) DeepCopy() *AceSetupInlineConfig {
	if in == nil {
		return nil
	}
	out := new(AceSetupInlineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPIClusterCreateOptions) DeepCopyInto(out *CAPIClusterCreateOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPIClusterCreateOptions.
func (in *CAPIClusterCreateOptions) DeepCopy() *CAPIClusterCreateOptions {
	if in == nil {
		return nil
	}
	out := new(CAPIClusterCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketplaceConfig) DeepCopyInto(out *MarketplaceConfig) {
	*out = *in
	out.AWS = in.AWS
	out.Azure = in.Azure
	out.GoogleCloud = in.GoogleCloud
	out.ClusterCreateOptions = in.ClusterCreateOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketplaceConfig.
func (in *MarketplaceConfig) DeepCopy() *MarketplaceConfig {
	if in == nil {
		return nil
	}
	out := new(MarketplaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConfig) DeepCopyInto(out *NatsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConfig.
func (in *NatsConfig) DeepCopy() *NatsConfig {
	if in == nil {
		return nil
	}
	out := new(NatsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfManagement) DeepCopyInto(out *SelfManagement) {
	*out = *in
	if in.EnableFeatures != nil {
		in, out := &in.EnableFeatures, &out.EnableFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisableFeatures != nil {
		in, out := &in.DisableFeatures, &out.DisableFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfManagement.
func (in *SelfManagement) DeepCopy() *SelfManagement {
	if in == nil {
		return nil
	}
	out := new(SelfManagement)
	in.DeepCopyInto(out)
	return out
}
