/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudProviders implements CloudProviderInterface
type FakeCloudProviders struct {
	Fake *FakeCloudV1alpha1
}

var cloudprovidersResource = schema.GroupVersionResource{Group: "cloud.bytebuilders.dev", Version: "v1alpha1", Resource: "cloudproviders"}

var cloudprovidersKind = schema.GroupVersionKind{Group: "cloud.bytebuilders.dev", Version: "v1alpha1", Kind: "CloudProvider"}

// Get takes name of the cloudProvider, and returns the corresponding cloudProvider object, and an error if there is any.
func (c *FakeCloudProviders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(cloudprovidersResource, name), &v1alpha1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudProvider), err
}

// List takes label and field selectors, and returns the list of CloudProviders that match those selectors.
func (c *FakeCloudProviders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CloudProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(cloudprovidersResource, cloudprovidersKind, opts), &v1alpha1.CloudProviderList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CloudProviderList{ListMeta: obj.(*v1alpha1.CloudProviderList).ListMeta}
	for _, item := range obj.(*v1alpha1.CloudProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudProviders.
func (c *FakeCloudProviders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(cloudprovidersResource, opts))
}

// Create takes the representation of a cloudProvider and creates it.  Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Create(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.CreateOptions) (result *v1alpha1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(cloudprovidersResource, cloudProvider), &v1alpha1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudProvider), err
}

// Update takes the representation of a cloudProvider and updates it. Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Update(ctx context.Context, cloudProvider *v1alpha1.CloudProvider, opts v1.UpdateOptions) (result *v1alpha1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(cloudprovidersResource, cloudProvider), &v1alpha1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudProvider), err
}

// Delete takes name of the cloudProvider and deletes it. Returns an error if one occurs.
func (c *FakeCloudProviders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(cloudprovidersResource, name, opts), &v1alpha1.CloudProvider{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudProviders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(cloudprovidersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CloudProviderList{})
	return err
}

// Patch applies the patch and returns the patched cloudProvider.
func (c *FakeCloudProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(cloudprovidersResource, name, pt, data, subresources...), &v1alpha1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudProvider), err
}
