/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "go.bytebuilders.dev/resource-model/apis/ui/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// OptionsEditorLister helps list OptionsEditors.
// All objects returned here must be treated as read-only.
type OptionsEditorLister interface {
	// List lists all OptionsEditors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OptionsEditor, err error)
	// Get retrieves the OptionsEditor from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.OptionsEditor, error)
	OptionsEditorListerExpansion
}

// optionsEditorLister implements the OptionsEditorLister interface.
type optionsEditorLister struct {
	indexer cache.Indexer
}

// NewOptionsEditorLister returns a new OptionsEditorLister.
func NewOptionsEditorLister(indexer cache.Indexer) OptionsEditorLister {
	return &optionsEditorLister{indexer: indexer}
}

// List lists all OptionsEditors in the indexer.
func (s *optionsEditorLister) List(selector labels.Selector) (ret []*v1alpha1.OptionsEditor, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OptionsEditor))
	})
	return ret, err
}

// Get retrieves the OptionsEditor from the index for a given name.
func (s *optionsEditorLister) Get(name string) (*v1alpha1.OptionsEditor, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("optionseditor"), name)
	}
	return obj.(*v1alpha1.OptionsEditor), nil
}
