apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: bytebuilders
  name: clustercredentials.cluster.bytebuilders.dev
spec:
  group: cluster.bytebuilders.dev
  names:
    categories:
    - kubernetes
    - resource-model
    - appscode
    kind: ClusterCredential
    listKind: ClusterCredentialList
    plural: clustercredentials
    singular: clustercredential
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              awsCredential:
                properties:
                  accessKeyID:
                    type: string
                  secretAccessKey:
                    type: string
                required:
                - accessKeyID
                - secretAccessKey
                type: object
              azureCredential:
                properties:
                  clientID:
                    type: string
                  clientSecret:
                    type: string
                  subscriptionID:
                    type: string
                  tenantID:
                    type: string
                required:
                - clientID
                - clientSecret
                - subscriptionID
                - tenantID
                type: object
              digitalOceanCredential:
                properties:
                  token:
                    type: string
                required:
                - token
                type: object
              gceCredential:
                properties:
                  projectID:
                    type: string
                  serviceAccount:
                    type: string
                required:
                - projectID
                - serviceAccount
                type: object
              googleCredential:
                properties:
                  accessToken:
                    type: string
                  clientID:
                    type: string
                  clientSecret:
                    type: string
                  expiry:
                    format: int64
                    type: integer
                  refreshToken:
                    type: string
                  scopes:
                    items:
                      type: string
                    type: array
                required:
                - accessToken
                - clientID
                - clientSecret
                type: object
              linodeCredential:
                properties:
                  token:
                    type: string
                required:
                - token
                type: object
              name:
                type: string
              ownerID:
                format: int64
                type: integer
              packetCredential:
                properties:
                  apiKey:
                    type: string
                  projectID:
                    type: string
                required:
                - apiKey
                - projectID
                type: object
              provider:
                type: string
              scalewayCredential:
                properties:
                  organization:
                    type: string
                  token:
                    type: string
                required:
                - organization
                - token
                type: object
              vultrCredential:
                properties:
                  token:
                    type: string
                required:
                - token
                type: object
            required:
            - name
            - ownerID
            - provider
            type: object
          status:
            properties:
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this resource. It corresponds to the resource's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
