apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: bytebuilders
  name: clusterinfos.cluster.bytebuilders.dev
spec:
  group: cluster.bytebuilders.dev
  names:
    categories:
    - kubernetes
    - resource-model
    - appscode
    kind: ClusterInfo
    listKind: ClusterInfoList
    plural: clusterinfos
    singular: clusterinfo
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              createdAt:
                format: int64
                type: integer
              endpoint:
                type: string
              externalID:
                type: string
              initialKubernetesVersion:
                type: string
              initialNodeCount:
                format: int32
                type: integer
              location:
                type: string
              name:
                type: string
              ownerID:
                format: int64
                type: integer
              ownerName:
                type: string
              project:
                type: string
              provider:
                enum:
                - AKS
                - DigitalOcean
                - EKS
                - GKE
                - Linode
                - Packet
                - Scaleway
                - Vultr
                type: string
              uid:
                type: string
            required:
            - name
            - ownerID
            - uid
            type: object
          status:
            properties:
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this resource. It corresponds to the resource's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
              phase:
                description: Phase represents current status of the cluster
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
