/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/identity/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTeamUsers implements TeamUserInterface
type FakeTeamUsers struct {
	Fake *FakeIdentityV1alpha1
}

var teamusersResource = schema.GroupVersionResource{Group: "identity.bytebuilders.dev", Version: "v1alpha1", Resource: "teamusers"}

var teamusersKind = schema.GroupVersionKind{Group: "identity.bytebuilders.dev", Version: "v1alpha1", Kind: "TeamUser"}

// Get takes name of the teamUser, and returns the corresponding teamUser object, and an error if there is any.
func (c *FakeTeamUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TeamUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(teamusersResource, name), &v1alpha1.TeamUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TeamUser), err
}

// List takes label and field selectors, and returns the list of TeamUsers that match those selectors.
func (c *FakeTeamUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TeamUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(teamusersResource, teamusersKind, opts), &v1alpha1.TeamUserList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TeamUserList{ListMeta: obj.(*v1alpha1.TeamUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.TeamUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested teamUsers.
func (c *FakeTeamUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(teamusersResource, opts))
}

// Create takes the representation of a teamUser and creates it.  Returns the server's representation of the teamUser, and an error, if there is any.
func (c *FakeTeamUsers) Create(ctx context.Context, teamUser *v1alpha1.TeamUser, opts v1.CreateOptions) (result *v1alpha1.TeamUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(teamusersResource, teamUser), &v1alpha1.TeamUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TeamUser), err
}

// Update takes the representation of a teamUser and updates it. Returns the server's representation of the teamUser, and an error, if there is any.
func (c *FakeTeamUsers) Update(ctx context.Context, teamUser *v1alpha1.TeamUser, opts v1.UpdateOptions) (result *v1alpha1.TeamUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(teamusersResource, teamUser), &v1alpha1.TeamUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TeamUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTeamUsers) UpdateStatus(ctx context.Context, teamUser *v1alpha1.TeamUser, opts v1.UpdateOptions) (*v1alpha1.TeamUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(teamusersResource, "status", teamUser), &v1alpha1.TeamUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TeamUser), err
}

// Delete takes name of the teamUser and deletes it. Returns an error if one occurs.
func (c *FakeTeamUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(teamusersResource, name, opts), &v1alpha1.TeamUser{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTeamUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(teamusersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TeamUserList{})
	return err
}

// Patch applies the patch and returns the patched teamUser.
func (c *FakeTeamUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TeamUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(teamusersResource, name, pt, data, subresources...), &v1alpha1.TeamUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TeamUser), err
}
