/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/identity/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOrgUsers implements OrgUserInterface
type FakeOrgUsers struct {
	Fake *FakeIdentityV1alpha1
}

var orgusersResource = schema.GroupVersionResource{Group: "identity.bytebuilders.dev", Version: "v1alpha1", Resource: "orgusers"}

var orgusersKind = schema.GroupVersionKind{Group: "identity.bytebuilders.dev", Version: "v1alpha1", Kind: "OrgUser"}

// Get takes name of the orgUser, and returns the corresponding orgUser object, and an error if there is any.
func (c *FakeOrgUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OrgUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(orgusersResource, name), &v1alpha1.OrgUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrgUser), err
}

// List takes label and field selectors, and returns the list of OrgUsers that match those selectors.
func (c *FakeOrgUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OrgUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(orgusersResource, orgusersKind, opts), &v1alpha1.OrgUserList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OrgUserList{ListMeta: obj.(*v1alpha1.OrgUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.OrgUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested orgUsers.
func (c *FakeOrgUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(orgusersResource, opts))
}

// Create takes the representation of a orgUser and creates it.  Returns the server's representation of the orgUser, and an error, if there is any.
func (c *FakeOrgUsers) Create(ctx context.Context, orgUser *v1alpha1.OrgUser, opts v1.CreateOptions) (result *v1alpha1.OrgUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(orgusersResource, orgUser), &v1alpha1.OrgUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrgUser), err
}

// Update takes the representation of a orgUser and updates it. Returns the server's representation of the orgUser, and an error, if there is any.
func (c *FakeOrgUsers) Update(ctx context.Context, orgUser *v1alpha1.OrgUser, opts v1.UpdateOptions) (result *v1alpha1.OrgUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(orgusersResource, orgUser), &v1alpha1.OrgUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrgUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOrgUsers) UpdateStatus(ctx context.Context, orgUser *v1alpha1.OrgUser, opts v1.UpdateOptions) (*v1alpha1.OrgUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(orgusersResource, "status", orgUser), &v1alpha1.OrgUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrgUser), err
}

// Delete takes name of the orgUser and deletes it. Returns an error if one occurs.
func (c *FakeOrgUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(orgusersResource, name), &v1alpha1.OrgUser{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOrgUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(orgusersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OrgUserList{})
	return err
}

// Patch applies the patch and returns the patched orgUser.
func (c *FakeOrgUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OrgUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(orgusersResource, name, pt, data, subresources...), &v1alpha1.OrgUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OrgUser), err
}
